// <auto-generated />
using System;
using Fyp.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fyp.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240715130020_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fyp.Models.AcademicProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AcademicPrograms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Software Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Data Engineering"
                        });
                });

            modelBuilder.Entity("Fyp.Models.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Domains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Research"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Development"
                        });
                });

            modelBuilder.Entity("Fyp.Models.LecturerProgram", b =>
                {
                    b.Property<int>("LecturerId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("AcademicProgramId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("LecturerId", "AcademicProgramId");

                    b.HasIndex("AcademicProgramId");

                    b.ToTable("LecturerPrograms");
                });

            modelBuilder.Entity("Fyp.Models.Murid", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("AcademicSession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProposalId")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupervisorApprovalStatus")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            SupervisorApprovalStatus = 0
                        },
                        new
                        {
                            StudentId = 2,
                            SupervisorApprovalStatus = 0
                        },
                        new
                        {
                            StudentId = 3,
                            SupervisorApprovalStatus = 0
                        });
                });

            modelBuilder.Entity("Fyp.Models.Penilai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Evaluators");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        });
                });

            modelBuilder.Entity("Fyp.Models.Pensyarah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DomainId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCommitteeMember")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("Lecturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCommitteeMember = false
                        },
                        new
                        {
                            Id = 2,
                            IsCommitteeMember = false
                        },
                        new
                        {
                            Id = 3,
                            IsCommitteeMember = false
                        });
                });

            modelBuilder.Entity("Fyp.Models.Penyelia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Supervisors");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        });
                });

            modelBuilder.Entity("Fyp.Models.ProjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Research"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Development"
                        });
                });

            modelBuilder.Entity("Fyp.Models.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Evaluator1Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Evaluator1Id")
                        .HasColumnType("int");

                    b.Property<string>("Evaluator2Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Evaluator2Id")
                        .HasColumnType("int");

                    b.Property<int>("MuridId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ProposalDocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Result1")
                        .HasColumnType("int");

                    b.Property<int?>("Result2")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Evaluator1Id");

                    b.HasIndex("Evaluator2Id");

                    b.HasIndex("MuridId")
                        .IsUnique();

                    b.HasIndex("ProjectTypeId");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4ba614f4-4dce-4e01-bbbb-9c74818cd5aa",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "77995c74-b83e-43dd-b22d-f5b6ec911d60",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "a43145a2-20ea-437c-b950-2e9ed5f697ba",
                            Name = "Lecturer",
                            NormalizedName = "LECTURER"
                        },
                        new
                        {
                            Id = "e4f99058-9b5d-4d20-9463-358935bdf319",
                            Name = "Supervisor",
                            NormalizedName = "SUPERVISOR"
                        },
                        new
                        {
                            Id = "9f30bdb2-8589-4b7b-a01f-ca4ac8d2e4ca",
                            Name = "Evaluator",
                            NormalizedName = "EVALUATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "44a5a4c2-d1bd-49ad-93b0-dad3cda6ed36",
                            RoleId = "77995c74-b83e-43dd-b22d-f5b6ec911d60"
                        },
                        new
                        {
                            UserId = "148b5b0d-e46c-469b-bd50-96e0cbad0734",
                            RoleId = "a43145a2-20ea-437c-b950-2e9ed5f697ba"
                        },
                        new
                        {
                            UserId = "f417ac54-fa17-46e5-a0a4-cea386f52bbe",
                            RoleId = "4ba614f4-4dce-4e01-bbbb-9c74818cd5aa"
                        },
                        new
                        {
                            UserId = "a2245ee9-b54e-478c-89f0-4237c1f90b64",
                            RoleId = "e4f99058-9b5d-4d20-9463-358935bdf319"
                        },
                        new
                        {
                            UserId = "10895172-15a1-4493-a82d-47b4e148c669",
                            RoleId = "9f30bdb2-8589-4b7b-a01f-ca4ac8d2e4ca"
                        },
                        new
                        {
                            UserId = "de659213-174b-49ad-9768-a45b67acec8e",
                            RoleId = "77995c74-b83e-43dd-b22d-f5b6ec911d60"
                        },
                        new
                        {
                            UserId = "59da83f6-11b4-4789-b727-40bd23e41de2",
                            RoleId = "a43145a2-20ea-437c-b950-2e9ed5f697ba"
                        },
                        new
                        {
                            UserId = "9fd7ed6c-04a5-4ab6-8383-267d18c175cb",
                            RoleId = "4ba614f4-4dce-4e01-bbbb-9c74818cd5aa"
                        },
                        new
                        {
                            UserId = "f40c6a83-aea4-4e82-b15c-23b46e1457d6",
                            RoleId = "e4f99058-9b5d-4d20-9463-358935bdf319"
                        },
                        new
                        {
                            UserId = "65d3a093-e7a7-4771-b427-59d90ddcaa49",
                            RoleId = "9f30bdb2-8589-4b7b-a01f-ca4ac8d2e4ca"
                        },
                        new
                        {
                            UserId = "00e943a8-6e13-448a-9a3d-8902025f80d7",
                            RoleId = "77995c74-b83e-43dd-b22d-f5b6ec911d60"
                        },
                        new
                        {
                            UserId = "97610b7d-e1fd-4f58-a326-81e71b20584f",
                            RoleId = "a43145a2-20ea-437c-b950-2e9ed5f697ba"
                        },
                        new
                        {
                            UserId = "2fca439c-3d44-40f8-b10c-f7dc29c97dcd",
                            RoleId = "4ba614f4-4dce-4e01-bbbb-9c74818cd5aa"
                        },
                        new
                        {
                            UserId = "d51d948e-7122-4f14-873a-39c18c816ad3",
                            RoleId = "e4f99058-9b5d-4d20-9463-358935bdf319"
                        },
                        new
                        {
                            UserId = "f5c860b0-981a-4a1a-bb04-e8943489b50c",
                            RoleId = "9f30bdb2-8589-4b7b-a01f-ca4ac8d2e4ca"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Fyp.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<int?>("EvaluatorId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IcNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LecturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasIndex("EvaluatorId")
                        .IsUnique()
                        .HasFilter("[EvaluatorId] IS NOT NULL");

                    b.HasIndex("LecturerId")
                        .IsUnique()
                        .HasFilter("[LecturerId] IS NOT NULL");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasFilter("[StudentId] IS NOT NULL");

                    b.HasIndex("SupervisorId")
                        .IsUnique()
                        .HasFilter("[SupervisorId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "44a5a4c2-d1bd-49ad-93b0-dad3cda6ed36",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5b4cb0de-fb9b-4e15-ad0e-024ea567a537",
                            Email = "student1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT1@GMAIL.COM",
                            NormalizedUserName = "STUDENT1@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFZVHJqTp1cgacbAZnyUqixpnbGJ0jo32uchBOHy6x6rdhf56/TIQYS4Sn0x39Fs0Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "da3c9430-afc4-425b-bb9e-151c629bb6c7",
                            TwoFactorEnabled = false,
                            UserName = "student1@gmail.com",
                            Gender = "Male",
                            IcNumber = "001234567890",
                            Name = "John Doe",
                            Nationality = "Malaysia",
                            StreetAddress = "123 Main St",
                            StudentId = 1
                        },
                        new
                        {
                            Id = "de659213-174b-49ad-9768-a45b67acec8e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "986365da-698a-4c00-a046-d0590bea966a",
                            Email = "student2@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT2@GMAIL.COM",
                            NormalizedUserName = "STUDENT2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAvKRu+CTl5ci82n3ZYavJzWQ2hCDHZy7YYCkMB3J8NY/7Lg2SF9nuITYLvRryqrgA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "85e30bd7-3af3-4695-a4f8-8f7aa48da7e5",
                            TwoFactorEnabled = false,
                            UserName = "student2@gmail.com",
                            Gender = "Female",
                            IcNumber = "987654321012",
                            Name = "Jane Smith",
                            Nationality = "Malaysia",
                            StreetAddress = "456 Elm St",
                            StudentId = 2
                        },
                        new
                        {
                            Id = "00e943a8-6e13-448a-9a3d-8902025f80d7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "59bc52ee-1720-4393-b168-f04a05b7dcc0",
                            Email = "student3@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT3@GMAIL.COM",
                            NormalizedUserName = "STUDENT3@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAIrxi0uMHrt4pX1CSDODR2Gsnq5usho8QkRR4749V49SiHmn4EabbAXVZyhH9RAfA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fd227025-85a4-4d30-b2b8-9aae2427f4d5",
                            TwoFactorEnabled = false,
                            UserName = "student3@gmail.com",
                            Gender = "Male",
                            IcNumber = "123456789012",
                            Name = "Michael Johnson",
                            Nationality = "Malaysia",
                            StreetAddress = "789 Oak St",
                            StudentId = 3
                        },
                        new
                        {
                            Id = "148b5b0d-e46c-469b-bd50-96e0cbad0734",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d25605b4-34e4-4154-b480-c23ac4437c09",
                            Email = "lecturer1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "LECTURER1@GMAIL.COM",
                            NormalizedUserName = "LECTURER1@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ6NNCiEBj2UqGDb9pFYMVJTlNRmziAdPhzjFFwdtgXS1B5G4V7KCdEJlnFGbib9Iw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "273d35e4-dba6-4f17-97d9-7ddba6396813",
                            TwoFactorEnabled = false,
                            UserName = "lecturer1@gmail.com",
                            Gender = "Female",
                            IcNumber = "098765432101",
                            LecturerId = 1,
                            Name = "Dr. Emily Brown",
                            Nationality = "Malaysia",
                            StreetAddress = "321 Pine St"
                        },
                        new
                        {
                            Id = "59da83f6-11b4-4789-b727-40bd23e41de2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "65909e5d-d2af-441b-adf6-be9bed43860f",
                            Email = "lecturer2@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "LECTURER2@GMAIL.COM",
                            NormalizedUserName = "LECTURER2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECEOWfVhY+hlaDqujGVSgqerZw8nRDaG6kPKbMdXYTy85yfKY0lT0oFilVv5SwLPOQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e754b384-f917-4307-a8ac-028531b86930",
                            TwoFactorEnabled = false,
                            UserName = "lecturer2@gmail.com",
                            Gender = "Male",
                            IcNumber = "456789012345",
                            LecturerId = 2,
                            Name = "Dr. David Lee",
                            Nationality = "Malaysia",
                            StreetAddress = "654 Cedar St"
                        },
                        new
                        {
                            Id = "97610b7d-e1fd-4f58-a326-81e71b20584f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4829e1e7-09b2-473f-b339-d6eded7813bf",
                            Email = "lecturer3@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "LECTURER3@GMAIL.COM",
                            NormalizedUserName = "LECTURER3@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOy0pKUxc+BZQSwsf/A8593/2o0+OemfEGn8xLz4dE19OFFusucLS5ElOhL/ZWLeag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7c115e7f-c5ee-465a-886b-3f32bee055e2",
                            TwoFactorEnabled = false,
                            UserName = "lecturer3@gmail.com",
                            Gender = "Female",
                            IcNumber = "876543210987",
                            LecturerId = 3,
                            Name = "Dr. Sophia Miller",
                            Nationality = "France",
                            StreetAddress = "987 Birch St"
                        },
                        new
                        {
                            Id = "f417ac54-fa17-46e5-a0a4-cea386f52bbe",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cc4015ab-8b67-4269-b56a-c63d7ce5586c",
                            Email = "admin1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN1@GMAIL.COM",
                            NormalizedUserName = "ADMIN1@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFGqsAykOwBTDqPLszcLvWA9M+7jbgg0QUN+fdFL2NhwRgwT42hZ1tybKDioIeQcrw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ea122f26-cb1a-4358-a4aa-bf0129c1659c",
                            TwoFactorEnabled = false,
                            UserName = "admin1@gmail.com",
                            Gender = "Male",
                            IcNumber = "000",
                            Name = "Admin One",
                            Nationality = "Malaysia",
                            StreetAddress = "123 Admin St"
                        },
                        new
                        {
                            Id = "9fd7ed6c-04a5-4ab6-8383-267d18c175cb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6d8d3faf-8b44-4271-aa08-a59d6363c17e",
                            Email = "admin2@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN2@GMAIL.COM",
                            NormalizedUserName = "ADMIN2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELS06s5XcrKc5DsvVfuZbxqZvnLPUJYoJ4/9r6+Kx7/8JR0eJpss/Fa3+tMl4daOlA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "001d4227-9d57-4bd2-a589-4957ece90c85",
                            TwoFactorEnabled = false,
                            UserName = "admin2@gmail.com",
                            Gender = "Female",
                            IcNumber = "000",
                            Name = "Admin Two",
                            Nationality = "Malaysia",
                            StreetAddress = "124 Admin St"
                        },
                        new
                        {
                            Id = "2fca439c-3d44-40f8-b10c-f7dc29c97dcd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8b441a84-a924-4457-be4f-5541df98cfcf",
                            Email = "admin3@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN3@GMAIL.COM",
                            NormalizedUserName = "ADMIN3@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBq//U7idu/8ao09AOQqt+s3grJu5EloDmoBq4Rt/nqF0lo6Ls8EVvxK4Ee39pvdVQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5265eb64-ec94-4cbd-9329-539e827f4ba2",
                            TwoFactorEnabled = false,
                            UserName = "admin3@gmail.com",
                            Gender = "Male",
                            IcNumber = "000",
                            Name = "Admin Three",
                            Nationality = "Malaysia",
                            StreetAddress = "125 Admin St"
                        },
                        new
                        {
                            Id = "a2245ee9-b54e-478c-89f0-4237c1f90b64",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6a7b1017-1063-4429-be37-fbe851a944f9",
                            Email = "supervisor1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERVISOR1@GMAIL.COM",
                            NormalizedUserName = "SUPERVISOR1@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFsXKuHAbaq6CbHmDugv3HhzoOLVOLYJotQb/zl3NNeYcamNRu+spDPoT8n9pHplnw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "35951c99-d0fe-4f4a-84aa-9bc6ccf4ab6d",
                            TwoFactorEnabled = false,
                            UserName = "supervisor1@gmail.com",
                            Gender = "Female",
                            IcNumber = "654321098765",
                            Name = "Prof. Isabella Brown",
                            Nationality = "India",
                            StreetAddress = "159 Elmwood St",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = "f40c6a83-aea4-4e82-b15c-23b46e1457d6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2efee632-e193-4d35-891b-2e7ffe85ce1c",
                            Email = "supervisor2@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERVISOR2@GMAIL.COM",
                            NormalizedUserName = "SUPERVISOR2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGR0eAr18MsC6Re8eMDF1cKuLLOmOY3VAxdZOmx95E2rug1SS59VIu7+fchDymJaJA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1f456d87-1004-402a-904a-f543de663bd9",
                            TwoFactorEnabled = false,
                            UserName = "supervisor2@gmail.com",
                            Gender = "Male",
                            IcNumber = "567890123456",
                            Name = "Ts. Noah Taylor",
                            Nationality = "China",
                            StreetAddress = "951 Pinecrest St",
                            SupervisorId = 2
                        },
                        new
                        {
                            Id = "d51d948e-7122-4f14-873a-39c18c816ad3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b46450a0-86a9-4dde-81c2-c83eb19fe5a5",
                            Email = "supervisor3@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERVISOR3@GMAIL.COM",
                            NormalizedUserName = "SUPERVISOR3@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELlEjsQhxMt58/sd2UmgyLPhn0f+Ikv4lqmW3eTKtsnahufhmr0/IfsKJH7JqCRjQg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5c8bf42e-61b2-4298-856e-fb8876b4ee8e",
                            TwoFactorEnabled = false,
                            UserName = "supervisor3@gmail.com",
                            Gender = "Female",
                            IcNumber = "210987654321",
                            Name = "Dr. Sophia Rodriguez",
                            Nationality = "Malaysia",
                            StreetAddress = "753 Birchwood St",
                            SupervisorId = 3
                        },
                        new
                        {
                            Id = "10895172-15a1-4493-a82d-47b4e148c669",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b7ab425a-2f02-4b90-99a3-c8fcc5e1efb1",
                            Email = "evaluator1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EVALUATOR1@GMAIL.COM",
                            NormalizedUserName = "EVALUATOR1@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIbecBFmEkdiN96j4UwY8nCUEv98rzH0dl1bqIGHhGby+mmbdQrZjmhwWU17V5m+CA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "75026ab4-1417-4be8-80b9-a2dbf986c77c",
                            TwoFactorEnabled = false,
                            UserName = "evaluator1@gmail.com",
                            EvaluatorId = 1,
                            Gender = "Male",
                            IcNumber = "234567890123",
                            Name = "Mr. Ethan Harris",
                            Nationality = "South Korea",
                            StreetAddress = "852 Cedarwood St"
                        },
                        new
                        {
                            Id = "65d3a093-e7a7-4771-b427-59d90ddcaa49",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b32e263a-cba3-4a14-8534-a386ba826a3a",
                            Email = "evaluator2@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EVALUATOR2@GMAIL.COM",
                            NormalizedUserName = "EVALUATOR2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMSIQBOQPxoWaTL6/vyUuy/I7kkNZC9azp+pF91JZ8QpP3/yojChpHsnzqZm2bX2BA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5d424577-df3c-41dc-9ede-0405938b01f4",
                            TwoFactorEnabled = false,
                            UserName = "evaluator2@gmail.com",
                            EvaluatorId = 2,
                            Gender = "Female",
                            IcNumber = "765432109876",
                            Name = "Prof. Emma Young",
                            Nationality = "Malaysia",
                            StreetAddress = "753 Pine Lane"
                        },
                        new
                        {
                            Id = "f5c860b0-981a-4a1a-bb04-e8943489b50c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dc53081b-0a26-4781-9535-8314abb212de",
                            Email = "evaluator3@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EVALUATOR3@GMAIL.COM",
                            NormalizedUserName = "EVALUATOR3@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAOrmf6mB7dBgKStZNIQnGW+yZtIw5XOwQrRX6iBw0lr8Jn4Lcw+7ygPdgKIlnnKnA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "25bd42df-6baa-4ff9-aa8c-135a7d989834",
                            TwoFactorEnabled = false,
                            UserName = "evaluator3@gmail.com",
                            EvaluatorId = 3,
                            Gender = "Male",
                            IcNumber = "345678901234",
                            Name = "Ts. Mason Green",
                            Nationality = "Malaysia",
                            StreetAddress = "951 Oak Lane"
                        });
                });

            modelBuilder.Entity("Fyp.Models.LecturerProgram", b =>
                {
                    b.HasOne("Fyp.Models.AcademicProgram", "AcademicProgram")
                        .WithMany()
                        .HasForeignKey("AcademicProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fyp.Models.Pensyarah", "Lecturer")
                        .WithMany("LecturerPrograms")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicProgram");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("Fyp.Models.Murid", b =>
                {
                    b.HasOne("Fyp.Models.Penyelia", "Supervisor")
                        .WithMany("Students")
                        .HasForeignKey("SupervisorId");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Fyp.Models.Pensyarah", b =>
                {
                    b.HasOne("Fyp.Models.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId");

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("Fyp.Models.Proposal", b =>
                {
                    b.HasOne("Fyp.Models.Penilai", "Evaluator1")
                        .WithMany()
                        .HasForeignKey("Evaluator1Id");

                    b.HasOne("Fyp.Models.Penilai", "Evaluator2")
                        .WithMany()
                        .HasForeignKey("Evaluator2Id");

                    b.HasOne("Fyp.Models.Murid", "Murid")
                        .WithOne("Proposal")
                        .HasForeignKey("Fyp.Models.Proposal", "MuridId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fyp.Models.ProjectType", "ProjectType")
                        .WithMany()
                        .HasForeignKey("ProjectTypeId");

                    b.Navigation("Evaluator1");

                    b.Navigation("Evaluator2");

                    b.Navigation("Murid");

                    b.Navigation("ProjectType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fyp.Models.ApplicationUser", b =>
                {
                    b.HasOne("Fyp.Models.Penilai", "Evaluator")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("Fyp.Models.ApplicationUser", "EvaluatorId");

                    b.HasOne("Fyp.Models.Pensyarah", "Lecturer")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("Fyp.Models.ApplicationUser", "LecturerId");

                    b.HasOne("Fyp.Models.Murid", "Student")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("Fyp.Models.ApplicationUser", "StudentId");

                    b.HasOne("Fyp.Models.Penyelia", "Supervisor")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("Fyp.Models.ApplicationUser", "SupervisorId");

                    b.Navigation("Evaluator");

                    b.Navigation("Lecturer");

                    b.Navigation("Student");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Fyp.Models.Murid", b =>
                {
                    b.Navigation("ApplicationUser")
                        .IsRequired();

                    b.Navigation("Proposal")
                        .IsRequired();
                });

            modelBuilder.Entity("Fyp.Models.Penilai", b =>
                {
                    b.Navigation("ApplicationUser")
                        .IsRequired();
                });

            modelBuilder.Entity("Fyp.Models.Pensyarah", b =>
                {
                    b.Navigation("ApplicationUser")
                        .IsRequired();

                    b.Navigation("LecturerPrograms");
                });

            modelBuilder.Entity("Fyp.Models.Penyelia", b =>
                {
                    b.Navigation("ApplicationUser")
                        .IsRequired();

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
