// <auto-generated />
using System;
using Fyp.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fyp.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fyp.Models.AcademicProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AcademicPrograms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Software Engineering"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Data Engineering"
                        });
                });

            modelBuilder.Entity("Fyp.Models.Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Domains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Research"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Development"
                        });
                });

            modelBuilder.Entity("Fyp.Models.LecturerProgram", b =>
                {
                    b.Property<int>("LecturerId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("AcademicProgramId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("LecturerId", "AcademicProgramId");

                    b.HasIndex("AcademicProgramId");

                    b.ToTable("LecturerPrograms");
                });

            modelBuilder.Entity("Fyp.Models.Murid", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("AcademicSession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProposalId")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupervisorApprovalStatus")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            SupervisorApprovalStatus = 0
                        },
                        new
                        {
                            StudentId = 2,
                            SupervisorApprovalStatus = 0
                        },
                        new
                        {
                            StudentId = 3,
                            SupervisorApprovalStatus = 0
                        });
                });

            modelBuilder.Entity("Fyp.Models.Penilai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Evaluators");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        });
                });

            modelBuilder.Entity("Fyp.Models.Pensyarah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DomainId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCommitteeMember")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DomainId");

                    b.ToTable("Lecturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCommitteeMember = false
                        },
                        new
                        {
                            Id = 2,
                            IsCommitteeMember = false
                        },
                        new
                        {
                            Id = 3,
                            IsCommitteeMember = false
                        });
                });

            modelBuilder.Entity("Fyp.Models.Penyelia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Supervisors");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        });
                });

            modelBuilder.Entity("Fyp.Models.ProjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Research"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Development"
                        });
                });

            modelBuilder.Entity("Fyp.Models.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Evaluator1Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Evaluator1Id")
                        .HasColumnType("int");

                    b.Property<string>("Evaluator2Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Evaluator2Id")
                        .HasColumnType("int");

                    b.Property<int>("MuridId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ProposalDocumentUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Result1")
                        .HasColumnType("int");

                    b.Property<int?>("Result2")
                        .HasColumnType("int");

                    b.Property<string>("SupervisorComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Evaluator1Id");

                    b.HasIndex("Evaluator2Id");

                    b.HasIndex("MuridId")
                        .IsUnique();

                    b.HasIndex("ProjectTypeId");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7b42cb50-a42c-43eb-96f0-89c18338838b",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "5f166561-895e-44fb-ae65-0534840a7533",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "3048ebcf-efa0-4d94-8c20-3b35e9dabcae",
                            Name = "Lecturer",
                            NormalizedName = "LECTURER"
                        },
                        new
                        {
                            Id = "b97be726-8b24-40d7-9314-a70bbb417b3b",
                            Name = "Supervisor",
                            NormalizedName = "SUPERVISOR"
                        },
                        new
                        {
                            Id = "7b6e28e2-b51b-4684-9de1-1f9e16d5663e",
                            Name = "Evaluator",
                            NormalizedName = "EVALUATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "4ec56310-c888-4c47-a94e-975cf7f29828",
                            RoleId = "5f166561-895e-44fb-ae65-0534840a7533"
                        },
                        new
                        {
                            UserId = "6705cc9b-67ec-4fff-bda4-8b6b2f4c2d25",
                            RoleId = "3048ebcf-efa0-4d94-8c20-3b35e9dabcae"
                        },
                        new
                        {
                            UserId = "bcf21292-beba-45b6-9182-4f1184d041f9",
                            RoleId = "7b42cb50-a42c-43eb-96f0-89c18338838b"
                        },
                        new
                        {
                            UserId = "eefbbf88-a11d-4ee2-9000-70b71f8246f8",
                            RoleId = "b97be726-8b24-40d7-9314-a70bbb417b3b"
                        },
                        new
                        {
                            UserId = "e9338e92-59c1-4f33-9d25-bc994817a09b",
                            RoleId = "7b6e28e2-b51b-4684-9de1-1f9e16d5663e"
                        },
                        new
                        {
                            UserId = "4147f1c9-350e-4408-9c51-ee6356d03d57",
                            RoleId = "5f166561-895e-44fb-ae65-0534840a7533"
                        },
                        new
                        {
                            UserId = "8f4b7420-1680-410d-aeca-6b66e586b6b8",
                            RoleId = "3048ebcf-efa0-4d94-8c20-3b35e9dabcae"
                        },
                        new
                        {
                            UserId = "2b3f2307-24f6-43a5-af45-316add2fca61",
                            RoleId = "7b42cb50-a42c-43eb-96f0-89c18338838b"
                        },
                        new
                        {
                            UserId = "0b41b16f-84d5-46c7-bf56-9db7c1e65798",
                            RoleId = "b97be726-8b24-40d7-9314-a70bbb417b3b"
                        },
                        new
                        {
                            UserId = "0c05b7a1-7df5-4256-ac9d-b2da978e8135",
                            RoleId = "7b6e28e2-b51b-4684-9de1-1f9e16d5663e"
                        },
                        new
                        {
                            UserId = "76238e7e-e275-4a4d-9b20-80b7f00fd48c",
                            RoleId = "5f166561-895e-44fb-ae65-0534840a7533"
                        },
                        new
                        {
                            UserId = "652e8b6c-16b0-45ee-b82e-9f085eff94de",
                            RoleId = "3048ebcf-efa0-4d94-8c20-3b35e9dabcae"
                        },
                        new
                        {
                            UserId = "39d251c6-cbc5-46b2-967b-f7a0869711d1",
                            RoleId = "7b42cb50-a42c-43eb-96f0-89c18338838b"
                        },
                        new
                        {
                            UserId = "477f95ab-32cc-4d3f-8921-f31a79f89f28",
                            RoleId = "b97be726-8b24-40d7-9314-a70bbb417b3b"
                        },
                        new
                        {
                            UserId = "a8fb6ff3-c5ca-44b9-a758-ce253485738c",
                            RoleId = "7b6e28e2-b51b-4684-9de1-1f9e16d5663e"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Fyp.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<int?>("EvaluatorId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IcNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LecturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("int");

                    b.HasIndex("EvaluatorId")
                        .IsUnique()
                        .HasFilter("[EvaluatorId] IS NOT NULL");

                    b.HasIndex("LecturerId")
                        .IsUnique()
                        .HasFilter("[LecturerId] IS NOT NULL");

                    b.HasIndex("StudentId")
                        .IsUnique()
                        .HasFilter("[StudentId] IS NOT NULL");

                    b.HasIndex("SupervisorId")
                        .IsUnique()
                        .HasFilter("[SupervisorId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "4ec56310-c888-4c47-a94e-975cf7f29828",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5b5d6fff-d4b7-46cc-9d75-e99b5b0dfcbf",
                            Email = "student1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT1@GMAIL.COM",
                            NormalizedUserName = "STUDENT1@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDSj/APZIcpO36Z/dPjUaxnkbw+71cciV3PRI8t4sgJWBKcGkC5sYFmNMFtH87/9kg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cfcdc034-4ca5-4b45-85e3-a6feefe29b4c",
                            TwoFactorEnabled = false,
                            UserName = "student1@gmail.com",
                            Gender = "Male",
                            IcNumber = "001234567890",
                            Name = "John Doe",
                            Nationality = "Malaysia",
                            StreetAddress = "123 Main St",
                            StudentId = 1
                        },
                        new
                        {
                            Id = "4147f1c9-350e-4408-9c51-ee6356d03d57",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a223546f-afd0-40d9-8f4a-d0350eb09fef",
                            Email = "student2@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT2@GMAIL.COM",
                            NormalizedUserName = "STUDENT2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG1Xtofza4Wq6By3EybS/Ump4i41CoS/zKSnDhqZkBmeVRnSD68m510FE5LixC5l6w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6a0780e0-e6c5-4169-a2d9-b6959e3033ab",
                            TwoFactorEnabled = false,
                            UserName = "student2@gmail.com",
                            Gender = "Female",
                            IcNumber = "987654321012",
                            Name = "Jane Smith",
                            Nationality = "Malaysia",
                            StreetAddress = "456 Elm St",
                            StudentId = 2
                        },
                        new
                        {
                            Id = "76238e7e-e275-4a4d-9b20-80b7f00fd48c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "809fb5e9-0759-482e-a131-16d0d21cd723",
                            Email = "student3@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT3@GMAIL.COM",
                            NormalizedUserName = "STUDENT3@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEC3XRyGJyw+Q0UFCk9eK3WC4AdpP2cfqpxqGpbvrmApGlJMlXa0n30AHB8N1nHXLKw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a885b0b9-f6fa-499c-9f53-85f38f3324a9",
                            TwoFactorEnabled = false,
                            UserName = "student3@gmail.com",
                            Gender = "Male",
                            IcNumber = "123456789012",
                            Name = "Michael Johnson",
                            Nationality = "Malaysia",
                            StreetAddress = "789 Oak St",
                            StudentId = 3
                        },
                        new
                        {
                            Id = "6705cc9b-67ec-4fff-bda4-8b6b2f4c2d25",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0be753d9-1acb-418e-b768-9300b1e13025",
                            Email = "lecturer1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "LECTURER1@GMAIL.COM",
                            NormalizedUserName = "LECTURER1@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEE0YHtgYWrq2IQnXO7ycZoCXbDqk2v7Ydgpa9F7DVCYcdQtSUpKNXqKbuJeSqZ+6Iw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "320d4394-089c-414d-824c-ec1f61970ca1",
                            TwoFactorEnabled = false,
                            UserName = "lecturer1@gmail.com",
                            Gender = "Female",
                            IcNumber = "098765432101",
                            LecturerId = 1,
                            Name = "Dr. Emily Brown",
                            Nationality = "Malaysia",
                            StreetAddress = "321 Pine St"
                        },
                        new
                        {
                            Id = "8f4b7420-1680-410d-aeca-6b66e586b6b8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "422626b3-6b42-4029-8d62-8b621014b69a",
                            Email = "lecturer2@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "LECTURER2@GMAIL.COM",
                            NormalizedUserName = "LECTURER2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDxNe1Y27sRsDn7VWqpms75af8FhkNyDgnSKxDnIsTtDhhuVTjYjYly8ltVfAR2qKg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "91ae36dc-e177-4a1f-9097-d5022813411d",
                            TwoFactorEnabled = false,
                            UserName = "lecturer2@gmail.com",
                            Gender = "Male",
                            IcNumber = "456789012345",
                            LecturerId = 2,
                            Name = "Dr. David Lee",
                            Nationality = "Malaysia",
                            StreetAddress = "654 Cedar St"
                        },
                        new
                        {
                            Id = "652e8b6c-16b0-45ee-b82e-9f085eff94de",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "efe09ba2-79dd-42fa-9401-834b62af2ef8",
                            Email = "lecturer3@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "LECTURER3@GMAIL.COM",
                            NormalizedUserName = "LECTURER3@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKktLqhy3EGHbgWStfuyqIizBt5BPwnFGDOCF3e3vYZi2fHZA/xk8ZC7gPdQwexkuA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c1cd46db-1460-4b62-94e4-b050e51f97cd",
                            TwoFactorEnabled = false,
                            UserName = "lecturer3@gmail.com",
                            Gender = "Female",
                            IcNumber = "876543210987",
                            LecturerId = 3,
                            Name = "Dr. Sophia Miller",
                            Nationality = "France",
                            StreetAddress = "987 Birch St"
                        },
                        new
                        {
                            Id = "bcf21292-beba-45b6-9182-4f1184d041f9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4dc912a0-5242-4248-a3f3-3ebeca3ec13a",
                            Email = "admin1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN1@GMAIL.COM",
                            NormalizedUserName = "ADMIN1@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPBDvlsiWN1vMlfosBsK7tDc5sNat5zB4CQBHxjA9EsKD1acPizGjVFbPQ0trKEw9w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fc1b0daa-ab39-43bc-b6dc-43c5ed73cd26",
                            TwoFactorEnabled = false,
                            UserName = "admin1@gmail.com",
                            Gender = "Male",
                            IcNumber = "000",
                            Name = "Admin One",
                            Nationality = "Malaysia",
                            StreetAddress = "123 Admin St"
                        },
                        new
                        {
                            Id = "2b3f2307-24f6-43a5-af45-316add2fca61",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e764bb3a-04fb-4eff-8989-05086b2a88ef",
                            Email = "admin2@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN2@GMAIL.COM",
                            NormalizedUserName = "ADMIN2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ4diMq+ztHp8S71nSQCvscYevFk6fWUpHA5UsTqkufN7LMIoQoePRU9ka9DGX/+dQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "732dc31f-618e-4ccc-b15a-f2fcade52336",
                            TwoFactorEnabled = false,
                            UserName = "admin2@gmail.com",
                            Gender = "Female",
                            IcNumber = "000",
                            Name = "Admin Two",
                            Nationality = "Malaysia",
                            StreetAddress = "124 Admin St"
                        },
                        new
                        {
                            Id = "39d251c6-cbc5-46b2-967b-f7a0869711d1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "73823f1d-7bd4-456f-b515-374f417f19d6",
                            Email = "admin3@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN3@GMAIL.COM",
                            NormalizedUserName = "ADMIN3@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIZUWspe9/H1KeQl3AAWCVgZTp1lmhzR6V/uDs8RJTQQaGWRu5aIzwVRePEidkVelQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a7ad67db-21ea-4e46-9351-52de89f4f4f9",
                            TwoFactorEnabled = false,
                            UserName = "admin3@gmail.com",
                            Gender = "Male",
                            IcNumber = "000",
                            Name = "Admin Three",
                            Nationality = "Malaysia",
                            StreetAddress = "125 Admin St"
                        },
                        new
                        {
                            Id = "eefbbf88-a11d-4ee2-9000-70b71f8246f8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "db5d8852-a450-451b-815f-7e87a8fad257",
                            Email = "supervisor1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERVISOR1@GMAIL.COM",
                            NormalizedUserName = "SUPERVISOR1@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEC3UZ2xWI62H4xbKx/2Y1zALRBe5IVpBfHHgG4LyKvfeKM+CA0jHHPcSHCO7vM9plg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ec242b0e-a2a5-45e0-9a52-840eb7060b35",
                            TwoFactorEnabled = false,
                            UserName = "supervisor1@gmail.com",
                            Gender = "Female",
                            IcNumber = "654321098765",
                            Name = "Prof. Isabella Brown",
                            Nationality = "India",
                            StreetAddress = "159 Elmwood St",
                            SupervisorId = 1
                        },
                        new
                        {
                            Id = "0b41b16f-84d5-46c7-bf56-9db7c1e65798",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "364a6ace-e4e5-4b5e-aa0b-8bce76f44ad9",
                            Email = "supervisor2@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERVISOR2@GMAIL.COM",
                            NormalizedUserName = "SUPERVISOR2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECQoPgHVFBxXIg2LIkAU95YybPSiakHloVIK/NmPE/6rjvzNjZlIjOtBucDXLKq3lg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2ffc38df-fb04-45cc-b442-d522c5257ea6",
                            TwoFactorEnabled = false,
                            UserName = "supervisor2@gmail.com",
                            Gender = "Male",
                            IcNumber = "567890123456",
                            Name = "Ts. Noah Taylor",
                            Nationality = "China",
                            StreetAddress = "951 Pinecrest St",
                            SupervisorId = 2
                        },
                        new
                        {
                            Id = "477f95ab-32cc-4d3f-8921-f31a79f89f28",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a37d6e55-56e2-47b6-a9e0-8eeea8a16faa",
                            Email = "supervisor3@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SUPERVISOR3@GMAIL.COM",
                            NormalizedUserName = "SUPERVISOR3@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG9pSYypb9QoEDASWNhmlgNKfIwAuGN/Fp2LrvwEsgd00tealyN9iH0U6DOY1ZdcQg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f91fb0e-0de6-4817-832c-158dce18e6af",
                            TwoFactorEnabled = false,
                            UserName = "supervisor3@gmail.com",
                            Gender = "Female",
                            IcNumber = "210987654321",
                            Name = "Dr. Sophia Rodriguez",
                            Nationality = "Malaysia",
                            StreetAddress = "753 Birchwood St",
                            SupervisorId = 3
                        },
                        new
                        {
                            Id = "e9338e92-59c1-4f33-9d25-bc994817a09b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ea200fe7-c342-44f2-a949-cc9cfcbf8fa1",
                            Email = "evaluator1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EVALUATOR1@GMAIL.COM",
                            NormalizedUserName = "EVALUATOR1@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEDZUXKuD0X7AfyaU0C1NKFnSJdpcUhenK977GLq+rXfVZtqMsRNagrTk5xWz7y5YcQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b4d62bd0-6c58-4a09-8aeb-bb658130f051",
                            TwoFactorEnabled = false,
                            UserName = "evaluator1@gmail.com",
                            EvaluatorId = 1,
                            Gender = "Male",
                            IcNumber = "234567890123",
                            Name = "Mr. Ethan Harris",
                            Nationality = "South Korea",
                            StreetAddress = "852 Cedarwood St"
                        },
                        new
                        {
                            Id = "0c05b7a1-7df5-4256-ac9d-b2da978e8135",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "845e0c16-1c03-4aa5-92f0-55aef6a48019",
                            Email = "evaluator2@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EVALUATOR2@GMAIL.COM",
                            NormalizedUserName = "EVALUATOR2@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPKpxnNsFu6gbcDekrw4kD84eLC+zZ9VnVEud5ne+uEMDMx5FkkZ5QmswKmMf9kDvQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "99b34f17-dc60-465b-a6d4-fe2d89056047",
                            TwoFactorEnabled = false,
                            UserName = "evaluator2@gmail.com",
                            EvaluatorId = 2,
                            Gender = "Female",
                            IcNumber = "765432109876",
                            Name = "Prof. Emma Young",
                            Nationality = "Malaysia",
                            StreetAddress = "753 Pine Lane"
                        },
                        new
                        {
                            Id = "a8fb6ff3-c5ca-44b9-a758-ce253485738c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d3c5b476-b0e1-4b13-a9a2-2ce69f17c97b",
                            Email = "evaluator3@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EVALUATOR3@GMAIL.COM",
                            NormalizedUserName = "EVALUATOR3@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKITF29lT7zMUsS8QXtrmJJXFiMflNy57t5bY5L9ZVDotiJvzT2Dnpgt6JbxYm8FWA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dd4ed535-648f-492b-8682-e929bd415274",
                            TwoFactorEnabled = false,
                            UserName = "evaluator3@gmail.com",
                            EvaluatorId = 3,
                            Gender = "Male",
                            IcNumber = "345678901234",
                            Name = "Ts. Mason Green",
                            Nationality = "Malaysia",
                            StreetAddress = "951 Oak Lane"
                        });
                });

            modelBuilder.Entity("Fyp.Models.LecturerProgram", b =>
                {
                    b.HasOne("Fyp.Models.AcademicProgram", "AcademicProgram")
                        .WithMany()
                        .HasForeignKey("AcademicProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fyp.Models.Pensyarah", "Lecturer")
                        .WithMany("LecturerPrograms")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicProgram");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("Fyp.Models.Murid", b =>
                {
                    b.HasOne("Fyp.Models.Penyelia", "Supervisor")
                        .WithMany("Students")
                        .HasForeignKey("SupervisorId");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Fyp.Models.Pensyarah", b =>
                {
                    b.HasOne("Fyp.Models.Domain", "Domain")
                        .WithMany()
                        .HasForeignKey("DomainId");

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("Fyp.Models.Proposal", b =>
                {
                    b.HasOne("Fyp.Models.Penilai", "Evaluator1")
                        .WithMany()
                        .HasForeignKey("Evaluator1Id");

                    b.HasOne("Fyp.Models.Penilai", "Evaluator2")
                        .WithMany()
                        .HasForeignKey("Evaluator2Id");

                    b.HasOne("Fyp.Models.Murid", "Murid")
                        .WithOne("Proposal")
                        .HasForeignKey("Fyp.Models.Proposal", "MuridId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fyp.Models.ProjectType", "ProjectType")
                        .WithMany()
                        .HasForeignKey("ProjectTypeId");

                    b.Navigation("Evaluator1");

                    b.Navigation("Evaluator2");

                    b.Navigation("Murid");

                    b.Navigation("ProjectType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fyp.Models.ApplicationUser", b =>
                {
                    b.HasOne("Fyp.Models.Penilai", "Evaluator")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("Fyp.Models.ApplicationUser", "EvaluatorId");

                    b.HasOne("Fyp.Models.Pensyarah", "Lecturer")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("Fyp.Models.ApplicationUser", "LecturerId");

                    b.HasOne("Fyp.Models.Murid", "Student")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("Fyp.Models.ApplicationUser", "StudentId");

                    b.HasOne("Fyp.Models.Penyelia", "Supervisor")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("Fyp.Models.ApplicationUser", "SupervisorId");

                    b.Navigation("Evaluator");

                    b.Navigation("Lecturer");

                    b.Navigation("Student");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Fyp.Models.Murid", b =>
                {
                    b.Navigation("ApplicationUser")
                        .IsRequired();

                    b.Navigation("Proposal")
                        .IsRequired();
                });

            modelBuilder.Entity("Fyp.Models.Penilai", b =>
                {
                    b.Navigation("ApplicationUser")
                        .IsRequired();
                });

            modelBuilder.Entity("Fyp.Models.Pensyarah", b =>
                {
                    b.Navigation("ApplicationUser")
                        .IsRequired();

                    b.Navigation("LecturerPrograms");
                });

            modelBuilder.Entity("Fyp.Models.Penyelia", b =>
                {
                    b.Navigation("ApplicationUser")
                        .IsRequired();

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
